INSERT INTO USER (ID, EMAIL, NAME) VALUES (1, 'eamoraes@gmail.com', 'Ederson');
INSERT INTO ITEM (ID, NAME , VALUE ) VALUES (1, 'Mouse', 10.99);
INSERT INTO ITEM (ID, NAME , VALUE ) VALUES (2, 'Keyboard', 79.99);